# -*- coding: utf-8 -*-
"""ClassWork02BIMAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0l9HGdGg2RyE3FFXo8V9m9E0J-ePZQt

All the information displayed on the PAN Card are in capital letters only. It doesn’t matter how you
entered the value. In the same way, Jesna is creating a form where she wants to take the input and
display the information only in capital letters. To help Jesna write a program in python that can make
any string value to the capital letters. Take the basic informations from the user and display it in capital
letters.
● Hint: Use isupper() method.
● ( Note: PAN is a 10-digit unique identification alphanumeric number (containing both alphabets and
numbers) assigned to Indians, mostly to those who pay tax. ... While PAN is a number, PAN Card is a
physical card that has your PAN as well as name, date of birth (DoB), and photograph.)
"""

pan=input("Enter your pan:").upper()
print("Your PAN is:",pan)

"""Yash and Vishal have invested 10000$ in their bank. Yash is getting 6% simple interest from his bank
and Vishal is getting 6% compound interest from his bank. Write a python program to calculate the
difference in their returns after 30 years. What is the difference in their return in one year? What is the
reason for this difference? Discuss
● Hint: Use the following parameters to calculate interest
● Principal amount
● Time
● Rate of interest
"""

principle=10000
roi=0.06
time=30
si=principle*time*roi
ci=(principle*(1+0.06)**time)-principle
print("total amount of yash's after 30 years " ,si)
print("total amount of visal's after 30 years " ,ci)

"""Shubh and Nidhi know how much they have scored in each subject in the examination. Now they want
to calculate the overall percentage they scored. Write a program to take marks of 5 subjects in the
examination and then print the overall percentage student has achieved.
"""

list1=["math","phy","chem","biology","eng"]
total = 500
namelist=["subh","nidhi"]
for i in namelist:
  count=0
  print(i)
  for i in list1:
    print(i,end=":")
    mark=int(input("enter your score:"))
    count=count+mark
  print(f"percentage of {i}:",(count/total)*100)

"""Vishnu is in third grade. He is curious to know how exactly any website verify whether given username and password
is correct or not. To explain the same thing to Vishnu create a basic signup and login system.
● Hint: Store the username and password inside variables signup and then use same variables for verification during
login process.
● Sample run:
● >> Create your account ( Signup )
● >> Enter username : Nidhi
● >> Enter password : 1234
● >> Confirm password : 1234
● >> Your account is created : D
● >> Login Here
● >> Enter username: Nidhi
● >> Enter password : 1234
● >> Login Successful : D
● Note:
● If confirm password is not correct while signup then print: password not matching
● If the username is not correct while login then print: Username not found
● If the password is not correct while login then print: Incorrect password. Login failed
● After any incorrect information stop the program using quit() function.
"""

username = input("Enter your username: ")
password = input("Enter your password: ")
confirm_password = input("Confirm your password: ")

if password == confirm_password:
  print("Your account is created.")
else:
  print("Password not matching.")
  quit()

while True:
  username_login = input("Enter your username: ")
  password_login = input("Enter your password: ")

  if username_login == username and password_login == password:
    print("Login successful.")
    break
  elif username_login != username:
    print("Username not found.")
  else:
    print("Incorrect password. Login failed.")
    break

"""A year consists of 365 days. But once in every four years, it consists of 366 days. And that is known as
a leap year. Shisha wants to know whether the current year is a leap year or not. She found that any
year divisible by 4 is a leap year, if the year is divisible by 100 then it will not be a leap year, and if the
year is divisible by 400 then it will be a leap year. Write a program in python to check whether the given
year is a leap year or not to help Shisha.
● Hint: Use if elif else condition
"""

year = int(input("Enter the year: "))
if year%100 ==0 and year%400 != 0 or year % 4 != 0:
  # if year % 100 == 0:
  #   if year % 400 == 0:
  #     print("The year is a leap year.")
  #   else:
  #     print("The year is not a leap year.")
  # else:
    print("The year is a not leap year.")
else:
  print("The year is a leap year.")

"""● At the same place where the bricklayer was working. So many red bricks were kept cubical. The
dimensions of the structure were 6 bricks x 6 bricks x 6 bricks. Chris wanted to count the number of
bricks, but he was not able to do that as all the bricks were not visible to him. To help Chris, write a
program in python to count the number of bricks available there using nested for loop. What is another
way to find the answer? Discuss.

"""

# method 1: using nested for loop
n = 6
count = 0
for i in range(n):
  for j in range(n):
    for k in range(n):
      count += 1
print("The number of bricks is", count)

# method 2: using formula
volume = n * n * n
count = volume / 6
print("The number of bricks is", count)

"""The Fibonacci sequence is a series of numbers in which each number is the sum of the two that
precede it. Starting at 0 and 1, the sequence looks like this: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, and so on
forever. The Fibonacci sequence can be described using a mathematical equation: Xn+2= Xn+1 + Xn.
● Arvind is very interested to know the 100th term of the Fibonacci series. He was adding the values
manually in a calculator but it was taking so much time for him to find any term of the Fibonacci series.
To help Arvind write a program that can print nth term of the Fibonacci series where n is the given term
by the user. Also, write the entire program inside a loop so that the user can use the program multiple
times without running the program again and again.
"""

n = int(input("Enter the number of terms: "))

f1 = 0
f2 = 1

if n <= 1:
  print("Invalid input")
elif n == 2:
  print(f1, f2)
else:
  print(f1, f2)
  for i in range(3, n + 1):
    f3 = f1 + f2
    print(f3)
    f1 = f2
    f2 = f3

"""Remo has got an assignment to write an essay with minimum 500 words. He really can't count how many words there are, as the essay is too big. Remo is seeking your help. So write a program in order to count the number of words in a file to help Remo.

Note: There might be commas in the sentences at times so make sure to replace the commas with the spaces so as soon as you read the file and store it in a variable make sure to replace the comma with spaces
"""

with open('essay.txt', 'r') as f:
  essay = f.read()
  essay = essay.replace(',', ' ')
  words = essay.split()
  word_count = len(words)
  print("The number of words in the essay is:", word_count)

"""Step Ahead a new school in New Jersey had a requirement like, for every new kid registered the principal wants to create a new file for that kid and store all his transactions in that file so that he can access it later for future reference. The principal should be able to add new data to the student's file whenever there is a new transaction by the kid like he graduated to a new class or if he wanted to take a transfer.

Now the principal wants to add new features to the previous requirements where he must be able to read the student's file that was created, should be able to rename the file and also should be able to delete an existing file if it is no longer needed
"""

with open('student_file.txt', 'w') as f:
  f.write('Student Name: John Doe\n')
  f.write('Student ID: 12345\n')
  f.write('Grade: 9\n')

with open('student_file.txt', 'r') as f:
  contents = f.read()
  print(contents)

with open('student_file.txt', 'a') as f:
  f.write('Graduated to Grade 10\n')

import os
os.rename('student_file.txt', 'john_doe_file.txt')

os.remove('john_doe_file.txt')

"""Edith, a Grade 5 kid, has to write 15 1-line stories as homework from her English teacher and she has very less time left for the same and she is not getting any ideas on how to write a one line story. Her brother Aaron is good at coding and wanted to help her sister and he has following scenarios as his idea :

Like we always know a story will start like either once upon a time, Yesterday etc so for "WHEN" Aaron has the following scenarios

WHEN = 'A few years ago', 'Yesterday', 'Last night', 'A long time ago','On 20th Jan'

Same way the next part of the story should a person, a animal or a thing i.e, "WHO" hence Aaron has the following options for "WHO"

WHO = 'a rabbit', 'an elephant', 'a mouse', 'a turtle','a cat'

The Next Part of the story would be "NAME" of a person, animal or a thing so Aaron has following as he options

NAME = 'Ali', 'Miriam','daniel', 'Hoouk', 'Starwalker'

So here comes one extra thing that can be just a sentence saying
"""

import random

WHEN = ['A few years ago', 'Yesterday', 'Last night', 'A long time ago', 'On 20th Jan']
WHO = ['a rabbit', 'an elephant', 'a mouse', 'a turtle', 'a cat']
NAME = ['Ali', 'Miriam', 'Daniel', 'Hoouk', 'Starwalker']

for i in range(15):
    when = random.choice(WHEN)
    who = random.choice(WHO)
    name = random.choice(NAME)

    story = f"{when}, {who} named {name}"
    print(story)

