# -*- coding: utf-8 -*-
"""numpay day 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-xJkHDxVJHcShhoXN4BB_nKxf9JkdJs
"""

import numpy as np

ary1 = np.random.randint(15,25,(9,))
ary1

ary1[4]

ary1[-3]

ary2 = np.random.randint(15,30,(4,6))
ary2

ary2[3,4]

ary2[-1,-2]

ary3 = np.random.randint(100,200,(4,6))
ary3

ary3.size

ary3.shape

ary3.itemsize #memory occupy by each element

ary3

ary4 = np.random.randint(100,200,(3,4,6))
ary4

ary4[1]

ary5 = np.random.randint(100,200,(2,3,4,6))
ary5

ary5[0,2,3,3]

ary1

ary1[2:7:1]#slicing

ary1[7:2:-1]

ary2

ary2[1:3] #here we print 1th row to 3rd row

ary2[1:3, : ] # after comma we are provide all the column here

ary2[1:3,2:4]

ary2[ : ,2 : 4]

ary2[2 : 4 :1 ,  2 :4 :1]

ary4

ary4[1:2:1,]

ary4[1:2:1,2:4:1,1:5:1]

ary4

ary4[0:3:1,1:4:1,2:5:1]

ary4[0:3:2,1:4:1,1:3:1] #using step

ary4

ary4[0:3:2]

ary4[0:3:2,0:4:1,1:6:2]

"""<h1>advance indexing</h1>"""

ary1

ary1[6]

ary1[1:8:1]

# 18,16,16,23
2,3,5,7         #their position on ary1

ary1[[2,3,5,7]]

ary2

#20,25,18,29,23,20,22
 #place all the row number first then after comma put all the column numbers
#  i.e, ary2[[0,1,2,3,2,1,0],[0,1,2,2,4,5,5]]

ary2[[0,1,2,3,2,1,0],[0,1,2,2,4,5,5]]

ary1

a = ary1>17
ary1>17

ary1[a]

ary2

b = ary2>20
b

ary2[b]

c = (ary2>17) & (ary2<25)
c #bitwise and that is i want values between 17 and 25

ary2[c]

ary2.size

ary2[c].size

a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b),axis = 0)

np.concatenate((a,b.T), axis =1)

x = np.arange(9.0)
x

np.split(x, 3)

np.split(x,[3,5,6,10] )

np.split(x,[3,4,5,6,7] )

