# -*- coding: utf-8 -*-
"""PANDAS DAY1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Ds5n6NTTfIsGFTabE1_g89RmtWfRLR0
"""

pip install pandas

import pandas as pd

"""**CREATING SERIES WITH VALUES**"""

s1 = pd.Series([100,200,300,400])

s1

s1[2]

"""**different ways of creating a series**


*   values
*   variables
*   list
*   scalar
*   numpy array
*   dictionary




"""

a = 'blue'
b = 'green'
c = 'yellow'
d = 'pink'

s2 = pd.Series([a,b,c,d])

s2

s2 = pd.Series([a,b,c,d],index = ['b','g','y','b'])

s2

