# -*- coding: utf-8 -*-
"""pandas day 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AwXCyhfeeHfMuEuMOOpi-tYjB_rkKujY
"""

import numpy as np

ary1 = np.array([100,200,300,400,500])

ary1

print(ary1)

type(ary1)

ary1.shape #to check the shape

ary1.ndim #to check the dimension

ary1.dtype #to check the data type

ary1.itemsize

ary2 = np.array([[10,20,30,40],[100,200,300,400]]) #2 dimwnsional array

print(ary2)

ary2.shape

ary2.ndim

ary2.size #to check number of scalar

"""**<h1>ones()</h1>**"""

np1 = np.ones((4,6))

print(np1)

np1[1,1]

np1[1,1] = "100"

print(np1)

np1.ndim

np3 = np.ones((2,4,6))

np3

np1

for i in np1:
  print(i)  #we are getting values row by row

for i in np3:
  print(i)  # we are getting block by block due to 3 dimension

for i in np3:
  print(i)
  print("------------------------------------------------")
  for j in i:
    print(j)
  print("------------------------------------------------")

"""<h1>ZEROS()</h1>

"""

z1 = np.zeros((3,5))

z1

e1 = np.eye(4)
e1 #get 1 diagonaly

e2 = np.eye(4,5)
e2

e21 = np.eye(4,4)
e21

np.identity(4)

e3 = np.eye(4,5,k=1)
e3                    #play with things

print(np.arange(20))
print("-----------------------")
print(np.arange(2,10))
print("-----------------------")
print(np.arange(2,30,3))
print("-----------------------")
print(np.arange(20,10,-1))

np.linspace(1,20,5)
#it will generate requested number of values between start and end values with equal interval

np.random.rand(2,4)

np.random.rand(2,4,5)

np.random.randn(2,4)

np.random.randint(2,6,(4,6))

np.random.randint(2,6,(2,4,6))

l1 = [11,200,333]

np.random.choice(l1,(4,6),p=(0.50,0.40,0.10))
# here we can choice which number is appear more number of time from l1

