# -*- coding: utf-8 -*-
"""population data cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goQXqzrBHkwHRSqNRKlpF49A48TNLkg1
"""

import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/world_population.csv")

print(df.info)

df.head(10)

df = df.sort_values(by='Rank', ascending=True)
df.head(10)

df.isnull().sum()

duplicate_rows = df.duplicated()
print("Number of duplicate rows:", duplicate_rows.sum())

# prompt: code to find a duplicate column in pandas

df_transpose = df.T
duplicate_columns = df_transpose.duplicated()
print("Number of duplicate columns:", duplicate_columns.sum())

df.columns = df.columns.str.upper()
df.columns

# df.rename(column = {' '})

df.groupby('CONTINENT').size().plot(kind='barh')

df.plot()

import matplotlib.pyplot as plt
import seaborn as sbn

asian_countries = df.loc[df["CONTINENT"]=="Asia"].sort_values(by=["2022 POPULATION"], ascending=False, ignore_index=True)

top_5_countries = asian_countries[["COUNTRY/TERRITORY", "2022 POPULATION"]].sort_values(by="2022 POPULATION", ascending=False).head(5)

sbn.barplot(data=top_5_countries, x="COUNTRY/TERRITORY", y="2022 POPULATION")
plt.xlabel("COUNTRY/TERRITORY")
plt.ylabel("2022 POPULATION")
plt.title("Top 5 Countries by Population in Asian Countries")

plt.show()

