# -*- coding: utf-8 -*-
"""ROCK PAPER SEASOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gMPD22HbWg499JwAF7W-o_Bwl-8i4kEG
"""

import random

def get_user_choice():
  choice = input("Enter your choice (rock, paper, scissors): ")
  return choice.lower()

def get_computer_choice():
  choices = ["rock", "paper", "scissors"]
  return random.choice(choices)

def determine_winner(user_choice, computer_choice):
  if user_choice == computer_choice:
    return "tie"
  elif user_choice == "rock" and computer_choice == "scissors":
    return "user"
  elif user_choice == "paper" and computer_choice == "rock":
    return "user"
  elif user_choice == "scissors" and computer_choice == "paper":
    return "user"
  else:
    return "computer"

def play_game():

  user_choice = get_user_choice()
  computer_choice = get_computer_choice()
  winner = determine_winner(user_choice, computer_choice)
  print(f"You chose {user_choice} and the computer chose {computer_choice}.")
  print(f"The winner is {winner}.")

play_game()

