# -*- coding: utf-8 -*-
"""SciAssign07BIMAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17vSAgDk86VGK1FTBaKGEaC49XZPbhLq-

Chirag, Yugank, and Chris decide to create a python program together. But they are not able to understand how they are going to divide the whole program among them. Also, they are confused with the combination process of the program as well. We can divide a big program into smaller parts known as functions. To explain the same thing to three students, write a python program and create different functions to add, subtract, and multiply two numbers.
"""

def add(a, b):
  c = a + b
  return c

def subtract(a, b):
  c = a - b
  return c

def multiply(a, b):
  c = a * b
  return c

add(1,2)

"""Sahil is wondering whether we can use the same concept of functions in creating simple and compound interest calculators. He is trying to create it but is unable to return the answers from the functions. Help him in doing the same

"""

def simple_interest(p, r, t):
  si = (p * r * t) / 100
  return si

def compound_interest(p, r, t):
  amount = p * (1 + (r / 100)) ** t
  ci = amount - p
  return ci

"""● Nidhi is writing a long program. She needs a function that can check whether a given number is a perfect square or not. To help Nidhi, write a program in python and create a function that checks whether the given number is a perfect square or not."""

def is_perfect_square(n):
  if n == 0:
    return True
  for i in range(1, int(n ** 0.5) + 1):
    if i * i == n:
      return True
  return False

"""Nidhi is creating a program in python for her school project. In between the program, she is converting numerical numbers into word format again and again. Then she realizes that she needs a function that can convert a number into word format with hyphens between each word. ( for example 57 = five-seven ). To help Nidhi create a function toWord() that can do the same thing. Hint: Use for loop and use if-elif-else condition Sample run: >> toWord(89) >> eight-nine >> toWord(398) >> three-nine-eight/"""

def toWord(n):
  num = str(n)
  units = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine']
  tens = ['ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen']
  tens_multiple = ['twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety']
  if len(num) == 1:
    return units[int(num)]
  elif len(num) == 2:
    if int(num[0]) == 1:
      return tens[int(num[1])]
    else:
      return tens_multiple[int(num[0]) - 2] + '-' + units[int(num[1])]
  elif len(num) == 3:
    if int(num[0]) == 0:
      return toWord(int(num[1:]) + ' hundred')
    else:
      return units[int(num[0])] + ' hundred' + ' ' + toWord(int(num[1:]))
  else:
    return 'number too large'

toWord(27)

"""There is a famous clothing store in a city, which has four different sub-branches under the main branch. End of each day four sub-branches should report back to the main branch about available stock in percentage.
write a python program and create four different branches and print just the available stock of each branch.
hint:#create four functions with name of your choice which should consists of one variable as total_stock, sold_stocks, available_stock and a print statement that prints the available stock value with a proper print statement

"""

def branch_report(branch_name, total_stock, sold_stocks):
    available_stock = total_stock - sold_stocks
    print(f"{branch_name} Branch - Available Stock: {available_stock}%")

branch_report("Branch A", 1000, 200)

branch_report("Branch B", 1500, 300)

branch_report("Branch C", 800, 100)

branch_report("Branch D", 1200, 250)