# -*- coding: utf-8 -*-
"""SciAssign06BIMAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VY_L_dl6FN-4pRTvQJ0dFGGIhuJ3f44H

In a classroom, there are desks arranged in a row and column fashion. The math teacher, Mr. James, asked one of the kid whose name was Robert to count the total number of desks present in the class. Robert was just wondering if there is software that could take the number of rows and number of columns and show how many desks there are that would make his job easier. So write a python program to help Robert to count the number of desks present in the class.Person Arrival Detector For James
"""

rows = int(input("Enter number of rows in the classroom: "))
cols = int(input("Enter number of columns in the classroom: "))
desks = rows * cols
print("The total number of desks in the classroom is:", desks)

"""Mr James, A businessman in canada was throwing a small party in a banquet hall and wanted to track the number of people attended the party so he kept a people tracker device in the entrance where every person enters is supposed to enter his or her authorization code to enter the hall, certain codes were assigned they are as follows :
If Banquet Hall Team Members like Manager, waiter, and Mr. James himself then their authorization code will be : 0
If Guests Their Authorization Code Will be : 1
If the Authorization Code Entered is 1 then increment the number_of_guests Variable by 1, Wish the Guest like
"Door Opened"
"Welcome to the Party, We Hope you have fun."
else If the Authorization Code Entered is 0 then print as follows
"Access Granted"
"Door Opened"
else tell the person that his entered number is invalid

"""

number_of_guests = 0
while True:
  code = int(input("Enter your authorization code: "))
  if code == 0:
    print("Access Granted")
    print("Door Opened")
  elif code == 1:
    number_of_guests += 1
    print("Door Opened")
    print("Welcome to the Party, We Hope you have fun.")
  else:
    print("Invalid authorization code")

"""Mathew, a 13 year old kid, is good at math but whenever it comes to the even and odd numbers he always faces difficulty to find the even or odd number greater than 10. So write a python program to help Mathew to print odd and even numbers in a certain range using a for loop."""

for i in range(11,21):
  if i%2 == 0:
    print(i,"is an even number")
  else:
    print(i,"is an odd number")

"""An online essay writing competition was held in a school. The students were required to write at least 250 words. According to the rule, only that essay should be checked which contains at least 250 words. Teachers were just guessing the number of words in the essay but that was not an accurate way to count the number of words. So write a program that can count the number of words in an essay ( Hint: Take input and count the number of words using for loop | Note: to count the number of words you can just count the number of blank spaces given in the input. )"""

essay = input("Enter your essay: ")
count = 0
for i in essay:
  if i == " ":
    count += 1
print("The number of words in the essay is:", count+1)

"""Create  a program that find the number is prime number or not."""

n=int(input("Enter a number"))
if n<=1:
    print("Not prime")
else:
    for i in range(2,n):
        if n%i==0:
            print("Not prime")
            break
    else:
        print("Prime")

"""Dictionary for Helbert To Manage his company students data it should perform as follows
In a company for each student an student id is provided to access the student details easily.
You can see there will be people with the same name . To avoid confusion each student should be provided with the an unique student ID
For example, there are two rajesh in the same company. There will be confusion if the management uses the name . So, an unique id
[10 : "Arjun" ,11 : "Rajesh",12 :"Rajesh " 13: "sathish"]
The management wants to send a message to each and every student.For that they are planning to use the student ID that they provided for each student. (Just print “message sent to : empid”)
There are two new students who are joining in this company and the management wants to assign student id to them also and want to add their data in the existing student details.
first create an empty dictionary and add those student details in that and merge

"""

data = {10: "Arjun", 11: "Rajesh", 12: "Rajesh", 13: "Sathish"}
new_data = {14: "John", 15: "Jen"}
data.update(new_data)
print(data)
for key, value in data.items():
  print("Message sent to:", key)

"""Create a student management program with all the operations on it."""

students = {}
while True:
    print("Welcome to the Student Management Program")
    print("-----------------------------------")
    print("1. Add a student")
    print("2. Edit a student")
    print("3. Delete a student")
    print("4. Search for a student")
    print("5. Print all students")
    print("6. Quit")
    choice = int(input("Enter your choice: "))
    if choice == 1:
        student_id = int(input("Enter the student ID: "))
        student_name = input("Enter the student name: ")
        student_age = int(input("Enter the student age: "))
        student_address = input("Enter the student address: ")
        students[student_id] = [student_name, student_age, student_address]
    elif choice == 2:
        student_id = int(input("Enter the student ID: "))
        if student_id in students:
            student_name = input("Enter the new student name: ")
            student_age = int(input("Enter the new student age: "))
            student_address = input("Enter the new student address: ")
            students[student_id] = [student_name, student_age, student_address]
        else:
            print("Student not found")
    elif choice == 3:
        student_id = int(input("Enter the student ID: "))
        if student_id in students:
            del students[student_id]
        else:
            print("Student not found")
    elif choice == 4:
        student_name = input("Enter the student name: ")
        for student_id, student_details in students.items():
            if student_details[0] == student_name:
                print("Student ID:", student_id)
                print("Student name:", student_details[0])
                print("Student age:", student_details[1])
                print("Student address:", student_details[2])
                break
        else:
            print("Student not found")
    elif choice == 5:
        for student_id, student_details in students.items():
            print("Student ID:", student_id)
            print("Student name:", student_details[0])
            print("Student age:", student_details[1])
            print("Student address:", student_details[2])
            print()
    elif choice == 6:
        break
    else:
        print("Invalid choice")

def quiz():
  score = 0

  print("1 + 1")
  answer = input()
  if answer == "2":
    score += 1

  print("2+2")
  answer = input()
  if answer == "4":
    score += 1

  print("4+4")
  answer = input()
  if answer == "8":
    score += 1

  print("8+8")
  answer = input()
  if answer == "16":
    score += 1

  print("Your score is", score, "out of 4")

quiz()

