# -*- coding: utf-8 -*-
"""SciAssignBIMAL08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ZTbQQjZ5pnXzWCQpmfK7tQo0v-gquY-

Priyanka wants to read a text file using python and she wants to print the content of that file in the terminal. But she is unable to specify the file name correctly. To help Priyanka write a program in python and show how to read the content of the text file and print it on the screen using python. ● Name of the text file: aboutPython.txt ● Content: ● Python is an interpreted, object-oriented, high-level programming language with dynamic semantics. It's high-level built in data structures, combined with dynamic typing and dynamic binding, make it very attractive for Rapid Application Development, as well as for use as a scripting or glue language to connect existing components together. Python's simple, easy to learn syntax emphasizes readability and therefore reduces the cost of program maintenance. Python supports modules and packages, which encourages program modularity and code reuse. The Python interpreter and the extensive standard library are available in source or binary form without charge for all major platforms, and can be freely distributed. ● . ● Hint: ● Create a text file aboutPython.txt ● Copy the given content in that file ● Using python read the content of the file. ● Use the concept of file handling.
"""

import os
import io
file_name = 'aboutpython.txt'
if os.path.exists(file_name):
    file_object = io.open(file_name, 'r')
    file_data = file_object.read()
    file_object.close()
    print(file_data)
else:
    print("File does not exist")

"""Himanshi has a text file and she wants to check whether that file contains any numerical value. So to help Himanshi write a python program that can check whether the text file includes any numerical value or not. As text files contain so many lines, so print the line number that has numerical values"""

# prompt: Himanshi has a text file and she wants to check whether that file contains any numerical value. So to help Himanshi write a python program that can check whether the text file includes any numerical value or not. As text files contain so many lines, so print the line number that has numerical values

import os
import re

file_name = 'aboutpython.txt'
if os.path.exists(file_name):
    file_object = io.open(file_name, 'r')
    file_data = file_object.read()
    file_object.close()
    lines = file_data.split('\n')
    for i, line in enumerate(lines):
        if re.search('[0-9]', line):
            print(f'Line number {i+1} contains a numerical value')
else:
    print("File does not exist")