''' IN PYTHON EVERYTHING IS AN OBJECT
TO CREATE A OBJECT WE REQUIRED A PLAN OR BLUEPRINT OR A MODEL WHICH IS NOTHING BUT A CLASS
THROUGH CLASS WE DO REPRESENT THE PROPERTIES AND ACTIONS OF A CLASS
THOSE PROPERTIES ARE REPRESENT AS VARIABLE
AND THE ACTIONS ARE REPRESENTS AS METHOD '''


"HENCE CLASS CONTAINS BOTH VARIABLES AND METHODS"


class Student:
    """ THIS IS A STUDENT CLASS WITH REQUIRED DATA"""
    def__init__(self);
    self.name = "durga"
    self.age = 40
    print(Student.__doc__)
    help(Student)
